name: Test
on:
  # Run CI on all pushes to the master and release/** branches, and on all new
  # pull requests, and on all pushes to pull requests (even if a pull request
  # is not against master).
  push:
    branches:
      - "master"
      - "release/**"
  pull_request:
  schedule:
    - cron: "0 0,12 * * *"

concurrency:
  group: ${{ github.ref_name || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
jobs:
  unit-test:
    if: github.repository_owner == 'getsentry'
    runs-on: ubuntu-22.04
    name: "unit tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Compose
        uses: ./get-compose-action

      - name: Unit Tests
        run: ./unit-test.sh

  integration-test:
    if: github.repository_owner == 'getsentry'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        container_engine: ['docker', 'podman']
    name: integration test (${{ matrix.container_engine }})
    env:
      REPORT_SELF_HOSTED_ISSUES: 0
      SELF_HOSTED_TESTING_DSN: ${{ vars.SELF_HOSTED_TESTING_DSN }}
      CONTAINER_ENGINE_PODMAN: ${{ matrix.container_engine == 'podman' && '1' || '0' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Podman
        if: matrix.container_engine == 'podman'
        run: |
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/Release.key \
           | gpg --dearmor \
           | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] \
            https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/ /" \
            | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          sudo apt-get -q update

      - name: Use action from local checkout
        uses: './'
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Inspect failure
        if: failure()
        run: |
          docker compose ps
          docker compose logs
